server:
  port: 80

eureka:
  client:
    #消费端不用向注册中心注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#配置Hystrix
feign:
  hystrix:
    enabled: true
