server:
  port: 8001

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wuwei.pojo
  config-location: classpath:mybatis-config.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 123456
#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      #注册中心的地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    #修改默认描述
    instance-id:  springcloud-provider-hystrix-dept8001
    #显示IP地址
    prefer-ip-address: true

#配置info信息
info:
  app.name: wuwei-springcloud
  company.name: blog.wuwei.com
