server:
  port: 9527


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

zuul:
  ignored-services: springcloud-provider-dept #不能使用这个路径访问了，就是隐藏了服务名
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
#  prefix: /wu  #设置公共的前缀



spring:
  application:
    name: springcloud-zuul